### ISSUE TITLE
请问这个项目是没有完成吗？

### ISSUE THREAD

**Issue by yingyulou** [yufeiran/OperatorSystem#1]

**Comment by yufeiran** [comment]
是的。暂时弃坑了😂，当时时间不太允许，所以我后面选择学xv6了，把Mit6.828/6.S081 Fall2020的lab全做了，https://github.com/yufeiran/xv6-labs-2020

**Comment by yingyulou** [comment]
Good！xv6的代码我感觉并不好懂啊TT
